name: Deploy Firestore meta settings on push/merge

on:
  push:
    branches:
      - main
    paths:
      - '.firebaserc'
      - '.github/workflows/prod-deploy-firestore-meta.yml'
      - 'firebase.json'
      - 'firebase.indexes.json'
      - 'firestore.rules'

jobs:
  build:
    name: Publish changes

    runs-on: ubuntu-latest

    steps:
      # Get the repo files from current commit
      - name: Cloning repository
        uses: actions/checkout@v1

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only=firestore --project=production
        env:
          GCP_SA_KEY: ${{ secrets.SERVICE_ACCOUNT_PRODUCTION }}

      - name: Send push notification
        env:
          MSG_TITLE: "Success: Production Firestore POAP QR Kiosk"
          MSG_CONTENT: "functions CI success"
        run: curl -f -X POST -d "token=${{ secrets.PUSHOVER_TOKEN }}&user=${{ secrets.PUSHOVER_USER }}&title=$MSG_TITLE&message=$MSG_CONTENT&priority=1" https://api.pushover.net/1/messages.json
        
      - name: Send failure push notification
        if: ${{ failure() }}
        env:
          MSG_TITLE: "Failure: Production Firestore POAP QR Kiosk"
          MSG_CONTENT: "functions CI failed"
        run: curl -f -X POST -d "token=${{ secrets.PUSHOVER_TOKEN }}&user=${{ secrets.PUSHOVER_USER }}&title=$MSG_TITLE&message=$MSG_CONTENT&priority=1" https://api.pushover.net/1/messages.json
        